projectId: app-vgLfYXYRR2BJQio69d4G5Z
appName: shoppinghouse
description: First application
imageURL: http://image.com/image
version: 1.0.0
hostName: ""
clusterURL: ""
clusterIPs: []
microservices:
  My-User-Service:
    serviceName: My-User-Service
    configs: []
    avgReplicas: 0
    minReplicas: 0
    maxReplicas: 0
    maxCPU: ""
    maxMemory: ""
    dockerImage: ""
    containerPort: 0
    envs: {}
    serviceEvaluation:
      kubeConfigType: []
  MyCart Service:
    serviceName: MyCart Service
    configs: []
    avgReplicas: 0
    minReplicas: 0
    maxReplicas: 0
    maxCPU: ""
    maxMemory: ""
    dockerImage: ""
    containerPort: 0
    envs: {}
    serviceEvaluation:
      kubeConfigType:
      - statefulSetBased
  MyOrderService:
    serviceName: MyOrderService
    configs: []
    avgReplicas: 0
    minReplicas: 0
    maxReplicas: 0
    maxCPU: ""
    maxMemory: ""
    dockerImage: ""
    containerPort: 0
    envs: {}
    serviceEvaluation:
      kubeConfigType: []
  mycartservice:
    serviceName: mycartservice
    configs: []
    avgReplicas: 0
    minReplicas: 0
    maxReplicas: 0
    maxCPU: ""
    maxMemory: ""
    dockerImage: ""
    containerPort: 0
    envs: {}
    serviceEvaluation:
      kubeConfigType:
      - statefulSetBased
  myorderservice:
    serviceName: myorderservice
    configs: []
    avgReplicas: 0
    minReplicas: 0
    maxReplicas: 0
    maxCPU: ""
    maxMemory: ""
    dockerImage: ""
    containerPort: 0
    envs: {}
    serviceEvaluation:
      kubeConfigType: []
  myuserservice:
    serviceName: myuserservice
    configs: []
    avgReplicas: 0
    minReplicas: 0
    maxReplicas: 0
    maxCPU: ""
    maxMemory: ""
    dockerImage: ""
    containerPort: 0
    envs: {}
    serviceEvaluation:
      kubeConfigType: []
monitoring: false
evaluationResult:
  language: Java
  database: MySQL
  hasdockerized: false
  haskubernetesservice: false
  haskubernetesdeployment: false
  microservices:
  - CartService
  - OrderService
  - UserService
