apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{.Values.appName}}'
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: '{{.Values.hostName}}'
    http:
      paths:
      - path: /{{.Values.microservices.MyCart Service.serviceName}}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: '{{.Values.microservices.MyCart Service.serviceName}}'
            port:
              name: http
      - path: /{{.Values.microservices.My-User-Service.serviceName}}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: '{{.Values.microservices.My-User-Service.serviceName}}'
            port:
              name: http
      - path: /{{.Values.microservices.mycartservice.serviceName}}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: '{{.Values.microservices.mycartservice.serviceName}}'
            port:
              name: http
      - path: /{{.Values.microservices.myuserservice.serviceName}}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: '{{.Values.microservices.myuserservice.serviceName}}'
            port:
              name: http
      - path: /{{.Values.microservices.myorderservice.serviceName}}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: '{{.Values.microservices.myorderservice.serviceName}}'
            port:
              name: http
      - path: /{{.Values.microservices.MyOrderService.serviceName}}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: '{{.Values.microservices.MyOrderService.serviceName}}'
            port:
              name: http
